title: Liffindra Angga Zaaldian

paginate: 5

plugins:
  - jekyll-seo-tag

social_links:
  - { platform: github,         user_url: "https://github.com/findrakecil" }
  - { platform: instagram,      user_url: "https://www.instagram.com/findrakecil" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/liffindrazaaldian" }